# Base configs
baseurl: "https://photography.rampatra.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Sam Photography"
subtitle: "See the world through my eyes!"
author: "Samuel Michel-Chagnot"
header:
 title: "Photography"
 subtitle: "Par Samuel"
footer:
 name: "Hey there, my name is Samuel"
 bio: "I have been passionate about photography for a few years now. it is a way for me to express my vision of what surrounds us and of subjects that I value."
 github: ""
web_design: "AJ"
social_urls:
  instagram: "https://www.instagram.com/sam_ul_mc"

